### ISSUE TITLE
Two meshes at the same chunk in the LOD example

### ISSUE THREAD

**Issue by Lemonzyy** [bonsairobo/building-blocks#35] opened 2021-07-19 19:57 UTC
In the LOD example, I found that two meshes are in the same location and overlap. I did not change any values in the configuration file.
![image](https://user-images.githubusercontent.com/47032639/126219336-5534ba1c-16f0-40f8-a7a4-d0fd0db39145.png)

**Comment by bonsairobo** [comment] 2021-07-23 00:53
This is most likely a bug with the clipmap algorithm.

**Comment by bonsairobo** [comment] 2021-08-18 06:46
This code has since changed a lot. If we can't reproduce this soon, I'm going to close the issue.

**Comment by bonsairobo** [comment] 2021-08-18 07:34
OK I actually managed to reproduce this, and reliably so. The trick is to quickly fly away from all of the terrain. Trying this enough times, it will reliably leave some chunks behind that never get despawned.

**Comment by bonsairobo** [comment] 2021-08-18 19:58
Although I fixed the common cause of this by switching from a clip cube to a clip sphere, this is actually still possible by tunneling through an entire LOD.

**Comment by bonsairobo** [comment] 2021-08-27 23:39
I think this is actually fixed now :crossed_fingers:

Closing until there is another repro after 7dcb50a27c5e

**Closed by bonsairobo** 2021-08-27 23:39 UTC
